/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freeguard;

/**
 *
 * @author still
 */
public class MainForm extends javax.swing.JFrame
{

    private static String email;
    private static String password;
    private static String firstName;
    private static String lastName;
    private static String middleInitial;
    private static String ssn;
    
    /**
     * Creates new form MainForm
     */
    public MainForm(String email, String password, String firstName, 
            String lastName, String middleInitial, String ssn)
    {
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleInitial = middleInitial;
        this.ssn = ssn;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        outputLabel = new javax.swing.JLabel();
        viewClaimsButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        submitClaimButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Free Guard");
        setAlwaysOnTop(true);
        setResizable(false);

        outputLabel.setText(" ");

        viewClaimsButton.setText("View Claims");
        viewClaimsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                viewClaimsButtonActionPerformed(evt);
            }
        });

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                settingsButtonActionPerformed(evt);
            }
        });

        submitClaimButton.setText("Submit Claim");
        submitClaimButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                submitClaimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewClaimsButton)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitClaimButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(outputLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewClaimsButton)
                    .addComponent(submitClaimButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewClaimsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_viewClaimsButtonActionPerformed
    {//GEN-HEADEREND:event_viewClaimsButtonActionPerformed
//        dispose();
        new ViewClaimForm(email);
    }//GEN-LAST:event_viewClaimsButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_settingsButtonActionPerformed
    {//GEN-HEADEREND:event_settingsButtonActionPerformed
        new SettingsForm(email, password, firstName, lastName, middleInitial, ssn).run();
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void submitClaimButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_submitClaimButtonActionPerformed
    {//GEN-HEADEREND:event_submitClaimButtonActionPerformed
        new SubmitClaimForm(ssn).run();
    }//GEN-LAST:event_submitClaimButtonActionPerformed

    public void run()
    {

        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainForm(email, password, firstName, lastName, middleInitial, ssn)
                        .setVisible(true);
            }
        });
    }
    
    //button to view claim
    //changes
    //sumbit claim

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton submitClaimButton;
    private javax.swing.JButton viewClaimsButton;
    // End of variables declaration//GEN-END:variables
}
